# Generated by Django 2.0.6 on 2018-06-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fack', '0002_topic_meta_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='excerpt',
            field=models.TextField(blank=True, help_text='The answer excerpt text.', verbose_name='excerpt'),
        ),
    ]
