# Generated by Django 2.0.7 on 2018-07-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fack', '0003_question_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='meta_desc',
            field=models.TextField(blank=True, help_text='The SEO meta description.', verbose_name='meta desc'),
        ),
    ]
